import prisma from '../config/db';
import { createChatCompletion } from '../config/ai';

/**
 * Handles the event when a PR comment thread is resolved.
 * Indicates that the suggestion was approved and resolved by the developer.
 */
export async function handleThreadResolved(thread: any): Promise<void> {
  const comments = thread.comments;
  if (!comments || comments.length === 0) return;

  // The first comment in the thread represents our bot's original review comment
  const rootComment = comments[0];
  const githubCommentId = String(rootComment.id);

  try {
    const updated = await prisma.reviewComment.updateMany({
      where: { githubCommentId },
      data: { status: 'APPROVED' },
    });

    if (updated.count > 0) {
      console.log(`[feedbackService] ReviewComment matching GitHub Comment ID ${githubCommentId} successfully marked as APPROVED.`);
    }
  } catch (error: any) {
    console.error(`[feedbackService] Error updating comment status on thread resolve:`, error.message);
  }
}

/**
 * Handles replies to our bot's review comments.
 * Employs lightweight AI sentiment analysis to determine if the review was accepted or rejected/disagreed.
 */
export async function handleReviewCommentCreated(comment: any): Promise<void> {
  // If this comment is not a reply, or is from a bot, skip
  if (!comment.in_reply_to_id || comment.user.type === 'Bot') return;

  const parentCommentId = String(comment.in_reply_to_id);
  const replyText = comment.body;

  // Verify the parent comment is one of ours in the DB
  const existingReview = await prisma.reviewComment.findUnique({
    where: { githubCommentId: parentCommentId },
  });

  if (!existingReview) {
    // Parent comment was not generated by our bot
    return;
  }

  // Perform sentiment/classification analysis on the developer response
  const prompt = `You are a developer sentiment classifier. Analyze this PR review reply and determine if the developer agrees/accepts the suggestion, or disagrees/rejects/marks it as a false positive.

Original Suggestion:
"${existingReview.explanation}"
Proposed Code:
"${existingReview.suggestion}"

Developer Reply:
"${replyText}"

Reply ONLY with "AGREE" if they accepted it, said thanks, or fixed it.
Reply ONLY with "DISAGREE" if they disagreed, rejected it, complained of a false positive, or explained why the suggestion is wrong/unwanted.
Do not output any other text.`;

  try {
    const classification = await createChatCompletion([
      { role: 'user', content: prompt }
    ]);

    if (!classification) return;

    const sanitizedClassification = classification.trim().toUpperCase();
    const isAgree = sanitizedClassification.includes('AGREE') && !sanitizedClassification.includes('DISAGREE');
    const status = isAgree ? 'APPROVED' : 'REJECTED';

    await prisma.reviewComment.update({
      where: { id: existingReview.id },
      data: {
        status,
        feedbackText: replyText,
      },
    });

    console.log(`[feedbackService] Updated ReviewComment ${existingReview.id} status to ${status} based on developer feedback: "${replyText}"`);
  } catch (error: any) {
    console.error(`[feedbackService] Error processing developer feedback:`, error.message);
  }
}
