const db = require('../config/db');
const ai = require('../config/ai');

/**
 * Handles the event when a PR comment thread is resolved.
 * Indicates that the suggestion was approved and resolved by the developer.
 * 
 * @param {Object} thread The thread object from GitHub Webhook payload
 */
async function handleThreadResolved(thread) {
  const comments = thread.comments;
  if (!comments || comments.length === 0) return;

  // The first comment in the thread represents our bot's original review comment
  const rootComment = comments[0];
  const githubCommentId = String(rootComment.id);

  try {
    const updated = await db.reviewComment.updateMany({
      where: { githubCommentId },
      data: { status: 'APPROVED' }
    });

    if (updated.count > 0) {
      console.log(`ReviewComment matching GitHub Comment ID ${githubCommentId} successfully marked as APPROVED.`);
    }
  } catch (error) {
    console.error(`Error updating comment status on thread resolve:`, error.message);
  }
}

/**
 * Handles replies to our bot's review comments.
 * Employs lightweight AI sentiment analysis to determine if the review was accepted or rejected/disagreed.
 * 
 * @param {Object} comment The reply comment object from GitHub Webhook payload
 */
async function handleReviewCommentCreated(comment) {
  // If this comment is not a reply, or is from a bot, skip
  if (!comment.in_reply_to_id || comment.user.type === 'Bot') return;

  const parentCommentId = String(comment.in_reply_to_id);
  const replyText = comment.body;

  // Verify the parent comment is one of ours in the DB
  const existingReview = await db.reviewComment.findUnique({
    where: { githubCommentId: parentCommentId }
  });

  if (!existingReview) {
    // Parent comment was not generated by our bot
    return;
  }

  // Perform sentiment/classification analysis on the developer response
  const prompt = `You are a developer sentiment classifier. Analyze this PR review reply and determine if the developer agrees/accepts the suggestion, or disagrees/rejects/marks it as a false positive.

Original Suggestion:
"${existingReview.explanation}"
Proposed Code:
"${existingReview.suggestion}"

Developer Reply:
"${replyText}"

Reply ONLY with "AGREE" if they accepted it, said thanks, or fixed it.
Reply ONLY with "DISAGREE" if they disagreed, rejected it, complained of a false positive, or explained why the suggestion is wrong/unwanted.
Do not output any other text.`;

  try {
    const classification = await ai.createChatCompletion([
      { role: 'user', content: prompt }
    ]);

    const sanitizedClassification = classification.trim().toUpperCase();
    const isAgree = sanitizedClassification === 'AGREE';
    const status = isAgree ? 'APPROVED' : 'REJECTED';

    await db.reviewComment.update({
      where: { id: existingReview.id },
      data: {
        status,
        feedbackText: replyText
      }
    });

    console.log(`Updated ReviewComment ${existingReview.id} status to ${status} based on developer feedback: "${replyText}"`);
  } catch (error) {
    console.error(`Error processing developer feedback:`, error.message);
  }
}

module.exports = {
  handleThreadResolved,
  handleReviewCommentCreated
};
